@@ .. @@
 -- Insertar plantillas de procedimientos (todas las 76)
 INSERT INTO plantillas_procedimientos (codigo, nombre, organismo, documentos_requeridos, etapas, dias_estimados, descripcion) VALUES
-  ('ANMAT-RNE', 'Registro Nacional de Establecimiento (RNE)', 'ANMAT', ARRAY['Formulario de solicitud', 'Plano del establecimiento', 'Certificado de habilitación municipal', 'Responsable técnico'], ARRAY['Solicitud', 'Revisión documentos', 'Inspección', 'Aprobación'], 30, 'Registro de establecimiento en ANMAT'),
-  ('SENASA-AFIDI', 'Autorización Fitosanitaria de Importación (AFIDI)', 'SENASA', ARRAY['Solicitud AFIDI', 'Factura proforma', 'Análisis de riesgo de plagas', 'Certificado fitosanitario'], ARRAY['Solicitud', 'Análisis', 'Aprobación'], 20, 'Autorización SENASA para importación'),
-  ('ENACOM-HOMO', 'Registro/homologación equipos telecomunicaciones', 'ENACOM', ARRAY['Solicitud de homologación', 'Ensayos de compatibilidad', 'Manual técnico', 'Certificado de origen'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Aprobación'], 45, 'Homologación de equipos de telecomunicaciones'),
-  ('DNRT-CONF', 'Certificación de Conformidad ex post', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Solicitud de certificación', 'Ensayos de laboratorio', 'Manual de usuario', 'Declaración de conformidad'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Certificación'], 35, 'Certificación de conformidad de productos');
+  -- ANMAT (12 procedimientos)
+  ('ANMAT-RNE', 'Registro Nacional de Establecimiento (RNE)', 'ANMAT', ARRAY['Formulario de solicitud', 'Plano del establecimiento', 'Certificado de habilitación municipal', 'Responsable técnico'], ARRAY['Solicitud', 'Revisión documentos', 'Inspección', 'Aprobación'], 30, 'Registro de establecimiento en ANMAT'),
+  ('ANMAT-RNPA', 'Registro Nacional de Producto Alimenticio (RNPA)', 'ANMAT', ARRAY['Formulario de solicitud', 'Análisis bromatológico', 'Etiqueta del producto', 'Certificado de libre venta'], ARRAY['Solicitud', 'Análisis', 'Evaluación', 'Aprobación'], 45, 'Registro de productos alimenticios'),
+  ('ANMAT-IMPORT', 'Autorización/Aviso de Importación', 'ANMAT', ARRAY['Solicitud de autorización', 'Factura comercial', 'Certificado de origen', 'Análisis del producto'], ARRAY['Solicitud', 'Revisión', 'Aprobación'], 15, 'Autorización para importación'),
+  ('ANMAT-LIBRE', 'Certificado de Libre Venta', 'ANMAT', ARRAY['Solicitud del certificado', 'RNPA vigente', 'Comprobante de pago'], ARRAY['Solicitud', 'Verificación', 'Emisión'], 10, 'Certificado de libre venta'),
+  ('ANMAT-HABEST', 'Habilitación de establecimientos', 'ANMAT', ARRAY['Formulario de habilitación', 'Planos técnicos', 'Manual de BPM', 'Certificado municipal'], ARRAY['Solicitud', 'Inspección', 'Evaluación', 'Habilitación'], 60, 'Habilitación de establecimientos'),
+  ('ANMAT-TRANSIT', 'Autorización tránsito interjurisdiccional', 'ANMAT', ARRAY['Solicitud de tránsito', 'Documentación del producto', 'Ruta de transporte'], ARRAY['Solicitud', 'Evaluación', 'Autorización'], 7, 'Autorización de tránsito'),
+  ('ANMAT-MODIF', 'Modificaciones al registro', 'ANMAT', ARRAY['Solicitud de modificación', 'Documentación actualizada', 'Justificación del cambio'], ARRAY['Solicitud', 'Evaluación', 'Aprobación'], 20, 'Modificaciones a registros existentes'),
+  ('ANMAT-PMI', 'Monitoreo ex post (PMI)', 'ANMAT', ARRAY['Declaración jurada', 'Documentación técnica', 'Certificados de calidad'], ARRAY['Declaración', 'Verificación', 'Monitoreo'], 15, 'Monitoreo posterior a la aprobación'),
+  ('ANMAT-NOINT', 'No intervención para usuarios directos', 'ANMAT', ARRAY['Solicitud de no intervención', 'Justificación técnica', 'Documentación del producto'], ARRAY['Solicitud', 'Evaluación', 'Resolución'], 10, 'No intervención ANMAT'),
+  ('ANMAT-COSMET', 'Registro de productos cosméticos', 'ANMAT', ARRAY['Formulario de registro', 'Fórmula cualitativa', 'Etiqueta del producto', 'Certificado de libre venta'], ARRAY['Solicitud', 'Evaluación', 'Registro'], 30, 'Registro de cosméticos'),
+  ('ANMAT-DOMISAN', 'Registro de domisanitarios', 'ANMAT', ARRAY['Solicitud de registro', 'Estudios de eficacia', 'Ficha de seguridad', 'Etiqueta y prospecto'], ARRAY['Solicitud', 'Estudios', 'Evaluación', 'Registro'], 90, 'Registro de productos domisanitarios'),
+  ('ANMAT-SUPENV', 'Registro de suplementos/envases', 'ANMAT', ARRAY['Formulario de registro', 'Certificado de aptitud', 'Análisis de migración', 'Especificaciones técnicas'], ARRAY['Solicitud', 'Análisis', 'Evaluación', 'Registro'], 45, 'Registro de suplementos y envases'),
+
+  -- ANMaC (5 procedimientos)
+  ('ANMAC-IMPORT', 'Autorización previa importación temporal/definitiva', 'ANMaC', ARRAY['Solicitud de autorización', 'Certificado de usuario legítimo', 'Factura comercial', 'Certificado de origen'], ARRAY['Solicitud', 'Verificación', 'Autorización'], 30, 'Autorización de importación de armas'),
+  ('ANMAC-REGISTRO', 'Registro armas/credencial tenencia', 'ANMaC', ARRAY['Formulario de registro', 'Certificado médico', 'Certificado de antecedentes', 'Comprobante de domicilio'], ARRAY['Solicitud', 'Verificación', 'Registro'], 45, 'Registro de armas y credenciales'),
+  ('ANMAC-HABILIMP', 'Habilitación importadores', 'ANMaC', ARRAY['Solicitud de habilitación', 'Estatuto social', 'Certificado de antecedentes', 'Garantía bancaria'], ARRAY['Solicitud', 'Evaluación', 'Habilitación'], 60, 'Habilitación de importadores'),
+  ('ANMAC-EXPRESS', 'Trámite exprés digital', 'ANMaC', ARRAY['Formulario digital', 'Documentación digitalizada', 'Comprobante de pago'], ARRAY['Solicitud digital', 'Procesamiento', 'Aprobación'], 5, 'Trámite digital express'),
+  ('ANMAC-RENOV', 'Renovación credenciales', 'ANMaC', ARRAY['Solicitud de renovación', 'Certificado médico actualizado', 'Comprobante de pago'], ARRAY['Solicitud', 'Verificación', 'Renovación'], 15, 'Renovación de credenciales'),
+
+  -- Dirección Nacional de Reglamentos Técnicos (19 procedimientos)
+  ('DNRT-CONF', 'Certificación de Conformidad ex post', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Solicitud de certificación', 'Ensayos de laboratorio', 'Manual de usuario', 'Declaración de conformidad'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Certificación'], 20, 'Certificación de conformidad de productos'),
+  ('DNRT-MARCADO', 'Marcado conformidad sello/QR', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Solicitud de marcado', 'Certificado de conformidad', 'Diseño del marcado'], ARRAY['Solicitud', 'Verificación', 'Aprobación'], 10, 'Marcado de conformidad'),
+  ('DNRT-CERTEXTR', 'Aceptación certificados extranjeros', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado extranjero', 'Traducción oficial', 'Solicitud de aceptación'], ARRAY['Solicitud', 'Verificación', 'Aceptación'], 15, 'Aceptación de certificados extranjeros'),
+  ('DNRT-DISPENS', 'Dispensación intervenciones previas', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Solicitud de dispensación', 'Justificación técnica', 'Documentación del producto'], ARRAY['Solicitud', 'Evaluación', 'Dispensación'], 20, 'Dispensación de intervenciones'),
+  ('DNRT-EXCEP', 'Excepciones regímenes certificación', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Solicitud de excepción', 'Fundamentos técnicos', 'Documentación alternativa'], ARRAY['Solicitud', 'Análisis', 'Resolución'], 30, 'Excepciones a regímenes'),
+  ('DNRT-EPP', 'Certificación EPP', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Solicitud de certificación', 'Ensayos de laboratorio', 'Manual de instrucciones', 'Marcado CE'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Certificación'], 45, 'Certificación de equipos de protección personal'),
+  ('DNRT-EFICIEN', 'Eficiencia energética', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Solicitud de etiquetado', 'Ensayos de eficiencia', 'Ficha técnica', 'Manual de usuario'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Etiquetado'], 30, 'Etiquetado de eficiencia energética'),
+  ('DNRT-SIMELA', 'Metrología legal (SIMELA)', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Solicitud de aprobación', 'Certificado de calibración', 'Manual técnico', 'Planos constructivos'], ARRAY['Solicitud', 'Evaluación técnica', 'Aprobación'], 60, 'Metrología legal'),
+  ('DNRT-ASCENS', 'Homologación ascensores', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Solicitud de homologación', 'Planos técnicos', 'Certificados de componentes', 'Manual de mantenimiento'], ARRAY['Solicitud', 'Evaluación técnica', 'Inspección', 'Homologación'], 90, 'Homologación de ascensores'),
+  ('DNRT-BICINFANT', 'Bicicletas de Uso Infantil', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de conformidad', 'Ensayos de seguridad', 'Manual de usuario', 'Etiquetado de seguridad'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Certificación'], 25, 'Certificación de bicicletas infantiles'),
+  ('DNRT-ENCEND', 'Encendedores', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de conformidad', 'Ensayos de seguridad', 'Instrucciones de uso', 'Marcado de seguridad'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Certificación'], 20, 'Certificación de encendedores'),
+  ('DNRT-PILAS', 'Pilas y Baterías', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de conformidad', 'Ensayos de seguridad', 'Etiquetado ambiental', 'Plan de gestión de residuos'], ARRAY['Solicitud', 'Ensayos', 'Evaluación ambiental', 'Certificación'], 30, 'Certificación de pilas y baterías'),
+  ('DNRT-PRODELEC', 'Productos Eléctricos para la Construcción', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de conformidad', 'Ensayos eléctricos', 'Manual de instalación', 'Marcado de seguridad'], ARRAY['Solicitud', 'Ensayos eléctricos', 'Evaluación', 'Certificación'], 35, 'Certificación de productos eléctricos'),
+  ('DNRT-SEGELEC', 'Seguridad Eléctrica', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de conformidad', 'Ensayos de seguridad eléctrica', 'Manual de usuario', 'Marcado de conformidad'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Certificación'], 40, 'Certificación de seguridad eléctrica'),
+  ('DNRT-ACEROS', 'Aceros para la Construcción', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de calidad', 'Ensayos mecánicos', 'Certificado de origen', 'Análisis químico'], ARRAY['Solicitud', 'Ensayos', 'Análisis', 'Certificación'], 25, 'Certificación de aceros'),
+  ('DNRT-CEMENT', 'Cementos', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de conformidad', 'Ensayos de resistencia', 'Análisis químico', 'Certificado de calidad'], ARRAY['Solicitud', 'Ensayos', 'Análisis', 'Certificación'], 30, 'Certificación de cementos'),
+  ('DNRT-MADERAS', 'Maderas y Compensado', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de conformidad', 'Ensayos de calidad', 'Certificado fitosanitario', 'Tratamiento NIMF-15'], ARRAY['Solicitud', 'Ensayos', 'Tratamiento', 'Certificación'], 20, 'Certificación de maderas'),
+  ('DNRT-GAFAS', 'Monturas de Gafas y Anteojos de Sol', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de conformidad', 'Ensayos ópticos', 'Certificado UV', 'Manual de usuario'], ARRAY['Solicitud', 'Ensayos ópticos', 'Evaluación', 'Certificación'], 25, 'Certificación de gafas y anteojos'),
+  ('DNRT-JUGUETES', 'Juguetes', 'Dirección Nacional de Reglamentos Técnicos', ARRAY['Certificado de conformidad', 'Ensayos de seguridad', 'Análisis de materiales', 'Etiquetado de edad'], ARRAY['Solicitud', 'Ensayos', 'Análisis', 'Certificación'], 35, 'Certificación de juguetes'),
+
+  -- ENACOM (3 procedimientos)
+  ('ENACOM-HOMO', 'Registro/homologación equipos telecomunicaciones', 'ENACOM', ARRAY['Solicitud de homologación', 'Ensayos de compatibilidad', 'Manual técnico', 'Certificado de origen'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Homologación'], 45, 'Homologación de equipos de telecomunicaciones'),
+  ('ENACOM-CERTCONF', 'Certificación conformidad', 'ENACOM', ARRAY['Certificado de conformidad', 'Ensayos técnicos', 'Declaración de conformidad', 'Manual de usuario'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Certificación'], 30, 'Certificación de conformidad ENACOM'),
+  ('ENACOM-EXCEP', 'Excepciones regímenes', 'ENACOM', ARRAY['Solicitud de excepción', 'Justificación técnica', 'Documentación alternativa'], ARRAY['Solicitud', 'Análisis', 'Resolución'], 20, 'Excepciones a regímenes ENACOM'),
+
+  -- ENARGAS (2 procedimientos)
+  ('ENARGAS-HOMO', 'Homologación de equipos y componentes para gas', 'ENARGAS', ARRAY['Solicitud de homologación', 'Ensayos de seguridad', 'Manual técnico', 'Certificado de calidad'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Homologación'], 60, 'Homologación de equipos de gas'),
+  ('ENARGAS-CERTSEG', 'Certificación de seguridad', 'ENARGAS', ARRAY['Certificado de seguridad', 'Ensayos de presión', 'Manual de instalación', 'Planos técnicos'], ARRAY['Solicitud', 'Ensayos', 'Evaluación', 'Certificación'], 45, 'Certificación de seguridad para gas'),
+
+  -- RENPRE (8 procedimientos)
+  ('RENPRE-INSCR', 'Inscripción y Reinscripción', 'RENPRE', ARRAY['Formulario de inscripción', 'Estatuto social', 'Certificado de antecedentes', 'Comprobante de domicilio'], ARRAY['Solicitud', 'Verificación', 'Inscripción'], 30, 'Inscripción en RENPRE'),
+  ('RENPRE-CERTIE', 'Certificados de Importación y Exportación', 'RENPRE', ARRAY['Solicitud de certificado', 'Factura comercial', 'Lista de empaque', 'Certificado de origen'], ARRAY['Solicitud', 'Verificación', 'Emisión'], 10, 'Certificados de comercio exterior'),
+  ('RENPRE-DESP', 'Presentación de despachos DGA', 'RENPRE', ARRAY['Despacho de importación/exportación', 'Documentación aduanera', 'Comprobantes de pago'], ARRAY['Presentación', 'Verificación', 'Aprobación'], 5, 'Presentación de despachos'),
+  ('RENPRE-MODIF', 'Modificaciones al registro', 'RENPRE', ARRAY['Solicitud de modificación', 'Documentación actualizada', 'Justificación del cambio'], ARRAY['Solicitud', 'Evaluación', 'Modificación'], 15, 'Modificaciones al registro'),
+  ('RENPRE-RENOV', 'Renovación anual de certificado', 'RENPRE', ARRAY['Solicitud de renovación', 'Balance del ejercicio', 'Comprobante de pago'], ARRAY['Solicitud', 'Verificación', 'Renovación'], 20, 'Renovación anual'),
+  ('RENPRE-CONSULT', 'Consultas de certificados', 'RENPRE', ARRAY['Solicitud de consulta', 'Número de certificado', 'Identificación del solicitante'], ARRAY['Consulta', 'Verificación', 'Respuesta'], 2, 'Consultas sobre certificados'),
+  ('RENPRE-AUTCOM', 'Autorizaciones para comercio exterior', 'RENPRE', ARRAY['Solicitud de autorización', 'Plan de negocios', 'Garantías bancarias'], ARRAY['Solicitud', 'Evaluación', 'Autorización'], 45, 'Autorizaciones de comercio exterior'),
+  ('RENPRE-IFA', 'Autorización Previa Importación IFA', 'RENPRE', ARRAY['Solicitud IFA', 'Factura proforma', 'Justificación de importación'], ARRAY['Solicitud', 'Evaluación', 'Autorización'], 15, 'Autorización previa IFA'),
+
+  -- Secretaría de Ambiente (6 procedimientos)
+  ('AMBIENTE-CITES', 'Certificado CITES import/export/reexport', 'Secretaría de Ambiente (Fauna/Flora CITES)', ARRAY['Solicitud CITES', 'Certificado de origen', 'Permiso del país de origen', 'Factura comercial'], ARRAY['Solicitud', 'Verificación', 'Emisión'], 30, 'Certificados CITES'),
+  ('AMBIENTE-FAUNA', 'Permiso de Importación de Fauna/Flora', 'Secretaría de Ambiente (Fauna/Flora CITES)', ARRAY['Solicitud de permiso', 'Certificado sanitario', 'Plan de manejo', 'Destino final'], ARRAY['Solicitud', 'Evaluación', 'Permiso'], 45, 'Permisos de fauna y flora'),
+  ('AMBIENTE-FLORA', 'Certificado de Flora Silvestre', 'Secretaría de Ambiente (Fauna/Flora CITES)', ARRAY['Solicitud de certificado', 'Identificación botánica', 'Origen de la flora', 'Uso previsto'], ARRAY['Solicitud', 'Identificación', 'Certificación'], 20, 'Certificados de flora silvestre'),
+  ('AMBIENTE-NOCOM', 'Autorización ambiental no comercial', 'Secretaría de Ambiente (Fauna/Flora CITES)', ARRAY['Solicitud de autorización', 'Justificación científica', 'Plan de investigación'], ARRAY['Solicitud', 'Evaluación científica', 'Autorización'], 25, 'Autorizaciones no comerciales'),
+  ('AMBIENTE-ANULA', 'Anulación de Certificados CITES', 'Secretaría de Ambiente (Fauna/Flora CITES)', ARRAY['Solicitud de anulación', 'Certificado original', 'Justificación de anulación'], ARRAY['Solicitud', 'Verificación', 'Anulación'], 10, 'Anulación de certificados'),
+  ('AMBIENTE-NOINT', 'No intervención para especies no listadas', 'Secretaría de Ambiente (Fauna/Flora CITES)', ARRAY['Solicitud de no intervención', 'Identificación de especies', 'Certificado de no inclusión'], ARRAY['Solicitud', 'Verificación', 'Certificación'], 15, 'No intervención de especies'),
+
+  -- SENASA (9 procedimientos)
+  ('SENASA-AFIDI', 'Autorización Fitosanitaria de Importación (AFIDI)', 'SENASA', ARRAY['Solicitud AFIDI', 'Factura proforma', 'Análisis de riesgo de plagas', 'Certificado fitosanitario'], ARRAY['Solicitud', 'Análisis de riesgo', 'Autorización'], 20, 'Autorización fitosanitaria de importación'),
+  ('SENASA-CERTSAN', 'Certificación sanitaria/fitosanitaria', 'SENASA', ARRAY['Solicitud de certificación', 'Análisis de laboratorio', 'Certificado de origen', 'Inspección sanitaria'], ARRAY['Solicitud', 'Análisis', 'Inspección', 'Certificación'], 15, 'Certificación sanitaria'),
+  ('SENASA-AUTOGEST', 'Inscripción simplificada por autogestión', 'SENASA', ARRAY['Formulario de autogestión', 'Declaración jurada', 'Comprobante de pago'], ARRAY['Solicitud', 'Verificación', 'Inscripción'], 10, 'Inscripción por autogestión'),
+  ('SENASA-EQUIV', 'Autorización por equivalencia para productos veterinarios', 'SENASA', ARRAY['Solicitud de equivalencia', 'Certificado de registro extranjero', 'Estudios de bioequivalencia', 'Dossier técnico'], ARRAY['Solicitud', 'Evaluación técnica', 'Estudios', 'Autorización'], 60, 'Equivalencia de productos veterinarios'),
+  ('SENASA-CPE', 'Cuarentena Post Entrada (CPE)', 'SENASA', ARRAY['Solicitud CPE', 'Plan de cuarentena', 'Instalaciones aprobadas', 'Protocolo sanitario'], ARRAY['Solicitud', 'Evaluación instalaciones', 'Cuarentena', 'Liberación'], 90, 'Cuarentena post entrada'),
+  ('SENASA-REGEST', 'Registro de establecimientos importadores', 'SENASA', ARRAY['Solicitud de registro', 'Plano del establecimiento', 'Manual de procedimientos', 'Responsable técnico'], ARRAY['Solicitud', 'Inspección', 'Evaluación', 'Registro'], 45, 'Registro de establecimientos'),
+  ('SENASA-APTIND', 'Certificado de aptitud para uso industrial', 'SENASA', ARRAY['Solicitud de aptitud', 'Proceso industrial', 'Análisis del producto', 'Destino final'], ARRAY['Solicitud', 'Evaluación proceso', 'Certificación'], 25, 'Aptitud para uso industrial'),
+  ('SENASA-FITOFERT', 'Certificado de Autorización de Importación de Fitosanitarios y Fertilizantes', 'SENASA', ARRAY['Solicitud de autorización', 'Registro del producto', 'Ficha de seguridad', 'Etiqueta del producto'], ARRAY['Solicitud', 'Evaluación', 'Autorización'], 30, 'Autorización de fitosanitarios'),
+  ('SENASA-DECLFIN', 'Declaración Fin de Fabricación/Importación', 'SENASA', ARRAY['Declaración jurada', 'Inventario final', 'Comprobantes de destrucción'], ARRAY['Declaración', 'Verificación', 'Cierre'], 15, 'Declaración de fin de actividad'),
+
+  -- Otros (12 procedimientos)
+  ('INV-VINOS', 'INV Certificados calidad/origen vinos/alcoholes', 'Otros', ARRAY['Solicitud de certificado', 'Análisis enológico', 'Certificado de origen', 'Registro de bodega'], ARRAY['Solicitud', 'Análisis', 'Certificación'], 20, 'Certificados de vinos y alcoholes'),
+  ('CTIT-DESBLQ', 'CTIT Solicitud de Desbloqueos', 'Otros', ARRAY['Solicitud de desbloqueo', 'Justificación técnica', 'Documentación del vehículo'], ARRAY['Solicitud', 'Evaluación', 'Desbloqueo'], 15, 'Desbloqueos CTIT'),
+  ('CTIT-TIPIF', 'CTIT Solicitudes de Tipificaciones por Admisión Temporaria 360 días/10 años', 'Otros', ARRAY['Solicitud de tipificación', 'Plan de uso temporal', 'Garantías bancarias', 'Cronograma de actividades'], ARRAY['Solicitud', 'Evaluación', 'Tipificación'], 30, 'Tipificaciones por admisión temporaria'),
+  ('CHAS-AUTOPART', 'CHAS Certificación Local de Autopartes', 'Otros', ARRAY['Solicitud de certificación', 'Especificaciones técnicas', 'Ensayos de calidad', 'Certificado de origen'], ARRAY['Solicitud', 'Ensayos', 'Certificación'], 45, 'Certificación de autopartes'),
+  ('CIVAC-CLASICOS', 'CIVAC Gestión de certificados de importación para vehículos clásicos', 'Otros', ARRAY['Solicitud CIVAC', 'Certificado de antigüedad', 'Documentación del vehículo', 'Valuación técnica'], ARRAY['Solicitud', 'Evaluación', 'Certificación'], 60, 'Certificados para vehículos clásicos'),
+  ('LCM-LCA', 'LCM/LCA Gestión de certificaciones para vehículos/componentes', 'Otros', ARRAY['Solicitud LCM/LCA', 'Certificado de conformidad', 'Ensayos de homologación', 'Manual técnico'], ARRAY['Solicitud', 'Ensayos', 'Homologación'], 45, 'Certificaciones LCM/LCA'),
+  ('DRAWBACK-TIP', 'Draw-Back Solicitud de Tipificación', 'Otros', ARRAY['Solicitud de tipificación', 'Plan de exportación', 'Insumos importados', 'Proceso productivo'], ARRAY['Solicitud', 'Evaluación', 'Tipificación'], 30, 'Tipificación para draw-back'),
+  ('EXPTEMP-PERF', 'Exportación Temporal para perfeccionamiento/repairs', 'Otros', ARRAY['Solicitud de exportación temporal', 'Contrato de reparación', 'Cronograma de trabajos', 'Garantías'], ARRAY['Solicitud', 'Evaluación', 'Autorización'], 20, 'Exportación temporal'),
+  ('IGM-MAPAS', 'IGM Intervención para mapas/cartográficos', 'Otros', ARRAY['Solicitud de intervención', 'Material cartográfico', 'Uso previsto', 'Autorización de uso'], ARRAY['Solicitud', 'Evaluación', 'Autorización'], 25, 'Intervención cartográfica'),
+  ('NIMF15-MAD', 'NIMF-15 Certificación maderas embalaje', 'Otros', ARRAY['Solicitud de certificación', 'Tratamiento fitosanitario', 'Certificado de origen', 'Marcado NIMF-15'], ARRAY['Solicitud', 'Tratamiento', 'Certificación'], 10, 'Certificación NIMF-15'),
+  ('VEH-ELECT', 'Vehículos Automotores Eléctricos Gestión de baja de Aranceles', 'Otros', ARRAY['Solicitud de beneficio', 'Certificado de vehículo eléctrico', 'Especificaciones técnicas', 'Plan de inversión'], ARRAY['Solicitud', 'Evaluación', 'Aprobación'], 45, 'Beneficios vehículos eléctricos'),
+  ('CIBU-USADOS', 'Declaración Jurada para importación de bienes usados (ex-CIBU)', 'Otros', ARRAY['Declaración jurada', 'Certificado de uso', 'Valuación técnica', 'Fotografías del bien'], ARRAY['Declaración', 'Evaluación', 'Aprobación'], 15, 'Importación de bienes usados');
 
 -- Insertar procesos de ejemplo